[package]
name = "twain"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.1"

[build-dependencies]
bindgen = "0.63.0"

[dev-dependencies]
assert-type-eq = "0.1.0"
libloading = "0.7.4"
